version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/oneby
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oneby
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    volumes:
      - ./mysql-data:/var/lib/mysql